#!/usr/bin/env bash

set -e

topdir=$(cd $(dirname $0)/..; pwd)
version=$(cat ${topdir}/.versioning/current)
projectname=semverutil

cd ${topdir}

[[ -d ./dist ]] && rm -rf ./dist
mkdir ./dist

tar \
    --exclude './build' \
    --exclude './dist' \
    --exclude './.git' \
    --exclude './.github' \
    --exclude './.cache' \
    --transform 's;^\.;'${projectname}'-'${version}';' \
    -cJf ./dist/${projectname}-source-${version}.tar.xz \
    .

cd ./dist
sha256sum ${projectname}-source-${version}.tar.xz >${projectname}-source-${version}.sha256

[[ -d "${topdir}/build" ]] || mkdir "${topdir}/build"

cmake -S "${topdir}" -B "${topdir}/build" --fresh -DCMAKE_BUILD_TYPE=Release -DSEMVERUTIL_STATIC_BINARY=ON
cmake --build "${topdir}/build" --clean-first

staticbin=$(find "${topdir}" -type f -executable -name ${projectname}-static | head -1)
if [[ -n "${staticbin}" ]]; then
    outname="${projectname}-static-$(uname -s)-$(uname -m)"
    cp "${staticbin}" "${topdir}/dist/${outname}"
    strip --strip-unneeded "${topdir}/dist/${outname}"
    sha256sum "${outname}" >"${outname}.sha256"
fi
